CREATE TABLE "STORAGE"
   ("ID" NUMBER,
    CONSTRAINT "STORAGE_PK" PRIMARY KEY ("ID"),
	"STRING_FORMAT" NVARCHAR2(20) NOT NULL ENABLE,
	"STORAGE_SIZE" NUMBER NOT NULL ENABLE,
	 CHECK (STRING_FORMAT = 'txt' OR STRING_FORMAT = 'jpg'));




CREATE TABLE FILE1
( ID NUMBER,
    CONSTRAINT "FILE_PK" PRIMARY KEY ("ID"),
    NAME NVARCHAR2(20) NOT NULL,
	FORMAT NVARCHAR2(20) NOT NULL,
	FILE_SIZE NUMBER NOT NULL,
	STORAGE_ID NUMBER,
    CONSTRAINT "STORAGE_FK" FOREIGN KEY ("STORAGE_ID") REFERENCES STORAGE("ID")  ON DELETE SET NULL);
