CREATE TABLE PLANE(
ID NUMBER,
  CONSTRAINT "PLANE_PK" PRIMARY KEY (ID),
P_NAME NVARCHAR2(40),
P_MODEL NVARCHAR2(40),
YEAR_PRODUCED DATE,
AVG_FUEL_CONSUMPTION NUMBER(10,2)
);


CREATE TABLE FLIGHT(
  ID NUMBER,
  CONSTRAINT "FLIGHT_PK" PRIMARY KEY (ID),
  PLANE_ID NUMBER,
  CONSTRAINT "PLANE_FK" FOREIGN KEY ("PLANE_ID") REFERENCES PLANE(ID),
  PASSENGER_ID NUMBER,

  DATE_FLIGHT DATE,
  CITY_FROM VARCHAR2(60),
  CITY_TO VARCHAR2(60)
);

CREATE TABLE PASSENGER (
  ID            NUMBER,
  CONSTRAINT "PASSENGER_PK" PRIMARY KEY (ID),
  LAST_NAME     VARCHAR2(100),
  NATIONALITY   VARCHAR2(60),
  DATE_OF_BIRTH DATE,
  PASS_CODE     VARCHAR2(40)

);

CREATE TABLE FLIGHT_AND_PASSENGER (
  FLIGHT_ID NUMBER REFERENCES FLIGHT(ID),
  PASSENGER_ID NUMBER REFERENCES PASSENGER(ID),
  PRIMARY KEY (FLIGHT_ID, PASSENGER_ID)
);